services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="db-78n9n" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD=db-78n9n
    expose:
      - 3306
      - 33060

  backend:
    build:
      context: backend
      target: builder
    restart: always
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      db:
        condition: service_healthy

